version: '3.8'
services:
  meKappfinal:
    image: markcustomer:v1 
    build: . # location of dockerfile 
    container_name: markcc0011
    ports:
    - "1167:80"
    restart: always 
    environment: 
      deploy: "app2"